"""The tmark IR as Python dataclasses, with a codec and a traversal.

The semantic document tree ``parse`` produces and ``write`` consumes, mirrored
in Python so a host can act on it between the two. :mod:`tmark.ir.model` is
generated from the IR schema by ``crates/tmark-py/scripts/gen_ir_models.py``
and checked in CI; :mod:`tmark.ir.codec` carries it across the binding, and
:mod:`tmark.ir.walk` traverses it.

It ships here rather than being regenerated by each host: the schema is this
repository's, so the mirror is too, and a field added to a node stops being a
change in two repositories.
"""

from __future__ import annotations

from tmark.ir import codec, model, walk


__all__ = ["codec", "model", "walk"]
