//! Emoji shortcodes: `:smile:` → the character it names.
//!
//! Spec §Emoji and icon shortcodes: "The name table is GitHub's (the
//! `gemoji` short names, which `pymdownx.emoji` ships as one of its
//! indexes)". The table is generated by `scripts/gen-emoji.py` from
//! `github/gemoji`'s `db/emoji.json` into `table.rs`; the crate stays
//! dependency-free. Icon shortcodes (`:material-…:`) are not emoji: the
//! four Material set prefixes are [`ICON_SETS`], and a shortcode starting
//! with one lowers to a web-only span.

mod table;

pub use table::EMOJI;

/// The prefixes of the MkDocs Material icon sets (spec §Emoji and icon
/// shortcodes): a shortcode `:<prefix>…:` names an SVG, not a character.
pub const ICON_SETS: &[&str] = &["material-", "fontawesome-", "octicons-", "simple-"];

/// The character of a `gemoji` shortcode (without the colons), or `None`
/// for a name the table does not know. Case-sensitive: the table is
/// lower-case, as PyMdownX's index is.
pub fn emoji(name: &str) -> Option<&'static str> {
    EMOJI
        .binary_search_by(|(alias, _)| alias.cmp(&name))
        .ok()
        .map(|i| EMOJI[i].1)
}

/// Whether `name` (without the colons) belongs to one of the Material
/// icon sets.
pub fn is_icon(name: &str) -> bool {
    ICON_SETS.iter().any(|set| name.starts_with(set))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lookup() {
        assert_eq!(emoji("smile"), Some("\u{1f604}"));
        assert_eq!(emoji("rocket"), Some("\u{1f680}"));
        assert_eq!(emoji("+1"), Some("\u{1f44d}"));
        assert_eq!(emoji("nope-not-an-emoji"), None);
        assert_eq!(emoji("Smile"), None, "shortcodes are lower-case");
        assert!(is_icon("material-cog") && is_icon("fontawesome-solid-check"));
        assert!(is_icon("octicons-tag-16") && is_icon("simple-github"));
        assert!(!is_icon("smile"));
    }

    #[test]
    fn table_is_sorted_and_unique() {
        for pair in EMOJI.windows(2) {
            assert!(pair[0].0 < pair[1].0, "{} before {}", pair[0].0, pair[1].0);
        }
        assert!(EMOJI.len() > 1800);
        assert!(EMOJI
            .iter()
            .all(|(name, c)| !name.is_empty() && !c.is_empty() && !name.contains(':')));
    }
}
