//! The CommonMark suite through the HTML writer (design 10-testing.md §2).
//! The examples are read from the vendored suite in
//! `crates/tmark-markdown/tests/commonmark.rs`; the ones listed in
//! `PASSING` render byte for byte as the reference implementation does.
//! The others are TMark's X-class deviations (`__x__`, `~x~`, `@word`,
//! `#[`, `---` … see the spec) or constructs the IR does not carry (raw
//! HTML blocks, entity references, image titles); the test prints the
//! score so a regression or a gain is visible.
//!
//! The fifteen "Emphasis and strong emphasis" examples whose whole
//! paragraph is one strong span are a deviation of the same kind: the
//! `paragraph.lead` feature (on by default, spec §Para) reads that shape
//! as a lead-in, so the HTML writer marks it `<strong class="lead">`.

use std::fs;
use std::path::Path;

use tmark_registry::{resolve, MemoryLoader, ResolveOptions};
use tmark_writers::{write, Backend, Media, WriterOptions};

/// `(input, expected, name)` triples of the suite file.
fn examples() -> Vec<(String, String, String)> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../tmark-markdown/tests/commonmark.rs");
    let text = fs::read_to_string(path).unwrap();
    let mut literals = Vec::new();
    let mut rest = text.as_str();
    while let Some(start) = rest.find("r###\"") {
        let after = &rest[start + 5..];
        let Some(end) = after.find("\"###") else {
            break;
        };
        literals.push(after[..end].to_string());
        rest = &after[end + 4..];
    }
    literals
        .chunks_exact(3)
        .map(|c| (c[0].clone(), c[1].clone(), c[2].clone()))
        .collect()
}

fn render(input: &str) -> String {
    let parsed = tmark_syntax::parse(input, tmark_ir::FileId::default());
    let resolved = resolve(
        &parsed.document,
        &MemoryLoader::new(),
        &ResolveOptions::default(),
    );
    let opts = WriterOptions {
        media: Media::Web,
        ..WriterOptions::default()
    };
    write(&parsed.document, &resolved, Backend::Html, &opts).text
}

/// Examples that must render exactly as the reference does.
const PASSING: &[&str] = &[
    "Tabs (1)",
    "Tabs (2)",
    "Tabs (3)",
    "Tabs (4)",
    "Tabs (8)",
    "Tabs (9)",
    "Tabs (10)",
    "Tabs (11)",
    "Backslash escapes (12)",
    "Backslash escapes (13)",
    "Backslash escapes (14)",
    "Backslash escapes (15)",
    "Backslash escapes (16)",
    "Backslash escapes (17)",
    "Backslash escapes (18)",
    "Backslash escapes (19)",
    "Backslash escapes (21)",
    "Backslash escapes (22)",
    "Backslash escapes (23)",
    "Backslash escapes (24)",
    "Entity and numeric character references (25)",
    "Entity and numeric character references (26)",
    "Entity and numeric character references (27)",
    "Entity and numeric character references (28)",
    "Entity and numeric character references (29)",
    "Entity and numeric character references (30)",
    "Entity and numeric character references (31)",
    "Entity and numeric character references (34)",
    "Entity and numeric character references (35)",
    "Entity and numeric character references (36)",
    "Entity and numeric character references (37)",
    "Entity and numeric character references (38)",
    "Entity and numeric character references (39)",
    "Entity and numeric character references (40)",
    "Entity and numeric character references (41)",
    "Precedence (42)",
    "Thematic breaks (43)",
    "Thematic breaks (44)",
    "Thematic breaks (45)",
    "Thematic breaks (46)",
    "Thematic breaks (47)",
    "Thematic breaks (48)",
    "Thematic breaks (49)",
    "Thematic breaks (50)",
    "Thematic breaks (51)",
    "Thematic breaks (52)",
    "Thematic breaks (53)",
    "Thematic breaks (54)",
    "Thematic breaks (55)",
    "Thematic breaks (56)",
    "Thematic breaks (57)",
    "Thematic breaks (58)",
    "Thematic breaks (59)",
    "Thematic breaks (60)",
    "ATX headings (62)",
    "ATX headings (63)",
    "ATX headings (64)",
    "ATX headings (65)",
    "ATX headings (66)",
    "ATX headings (67)",
    "ATX headings (68)",
    "ATX headings (69)",
    "ATX headings (70)",
    "ATX headings (71)",
    "ATX headings (72)",
    "ATX headings (73)",
    "ATX headings (74)",
    "ATX headings (75)",
    "ATX headings (76)",
    "ATX headings (77)",
    "ATX headings (78)",
    "ATX headings (79)",
    "Setext headings (80)",
    "Setext headings (81)",
    "Setext headings (82)",
    "Setext headings (83)",
    "Setext headings (84)",
    "Setext headings (85)",
    "Setext headings (86)",
    "Setext headings (87)",
    "Setext headings (88)",
    "Setext headings (89)",
    "Setext headings (90)",
    "Setext headings (91)",
    "Setext headings (92)",
    "Setext headings (93)",
    "Setext headings (94)",
    "Setext headings (95)",
    "Setext headings (97)",
    "Setext headings (99)",
    "Setext headings (100)",
    "Setext headings (101)",
    "Setext headings (102)",
    "Setext headings (103)",
    "Setext headings (104)",
    "Setext headings (105)",
    "Setext headings (106)",
    "Indented code blocks (107)",
    "Indented code blocks (108)",
    "Indented code blocks (110)",
    "Indented code blocks (111)",
    "Indented code blocks (112)",
    "Indented code blocks (113)",
    "Indented code blocks (114)",
    "Indented code blocks (115)",
    "Indented code blocks (116)",
    "Indented code blocks (117)",
    "Indented code blocks (118)",
    "Fenced code blocks (119)",
    "Fenced code blocks (120)",
    "Fenced code blocks (122)",
    "Fenced code blocks (123)",
    "Fenced code blocks (124)",
    "Fenced code blocks (125)",
    "Fenced code blocks (126)",
    "Fenced code blocks (127)",
    "Fenced code blocks (128)",
    "Fenced code blocks (129)",
    "Fenced code blocks (130)",
    "Fenced code blocks (131)",
    "Fenced code blocks (132)",
    "Fenced code blocks (133)",
    "Fenced code blocks (134)",
    "Fenced code blocks (135)",
    "Fenced code blocks (136)",
    "Fenced code blocks (137)",
    "Fenced code blocks (138)",
    "Fenced code blocks (139)",
    "Fenced code blocks (140)",
    "Fenced code blocks (141)",
    "Fenced code blocks (142)",
    "Fenced code blocks (143)",
    "Fenced code blocks (144)",
    "Fenced code blocks (145)",
    "Fenced code blocks (146)",
    "Fenced code blocks (147)",
    "HTML blocks (148)",
    "HTML blocks (149)",
    "HTML blocks (150)",
    "HTML blocks (151)",
    "HTML blocks (152)",
    "HTML blocks (153)",
    "HTML blocks (154)",
    "HTML blocks (155)",
    "HTML blocks (156)",
    "HTML blocks (157)",
    "HTML blocks (158)",
    "HTML blocks (159)",
    "HTML blocks (160)",
    "HTML blocks (161)",
    "HTML blocks (162)",
    "HTML blocks (163)",
    "HTML blocks (164)",
    "HTML blocks (165)",
    "HTML blocks (166)",
    "HTML blocks (167)",
    "HTML blocks (168)",
    "HTML blocks (169)",
    "HTML blocks (170)",
    "HTML blocks (171)",
    "HTML blocks (172)",
    "HTML blocks (173)",
    "HTML blocks (174)",
    "HTML blocks (176)",
    "HTML blocks (177)",
    "HTML blocks (178)",
    "HTML blocks (180)",
    "HTML blocks (181)",
    "HTML blocks (182)",
    "HTML blocks (184)",
    "HTML blocks (185)",
    "HTML blocks (186)",
    "HTML blocks (187)",
    "HTML blocks (188)",
    "HTML blocks (189)",
    "HTML blocks (190)",
    "HTML blocks (191)",
    "Link reference definitions (192)",
    "Link reference definitions (193)",
    "Link reference definitions (194)",
    "Link reference definitions (196)",
    "Link reference definitions (197)",
    "Link reference definitions (198)",
    "Link reference definitions (199)",
    "Link reference definitions (200)",
    "Link reference definitions (201)",
    "Link reference definitions (203)",
    "Link reference definitions (205)",
    "Link reference definitions (207)",
    "Link reference definitions (208)",
    "Link reference definitions (209)",
    "Link reference definitions (210)",
    "Link reference definitions (211)",
    "Link reference definitions (212)",
    "Link reference definitions (213)",
    "Link reference definitions (214)",
    "Link reference definitions (215)",
    "Link reference definitions (216)",
    "Link reference definitions (217)",
    "Paragraphs (219)",
    "Paragraphs (220)",
    "Paragraphs (221)",
    "Paragraphs (222)",
    "Paragraphs (223)",
    "Paragraphs (224)",
    "Paragraphs (225)",
    "Paragraphs (226)",
    "Blank lines (227)",
    "Block quotes (228)",
    "Block quotes (229)",
    "Block quotes (230)",
    "Block quotes (231)",
    "Block quotes (232)",
    "Block quotes (233)",
    "Block quotes (234)",
    "Block quotes (235)",
    "Block quotes (236)",
    "Block quotes (237)",
    "Block quotes (238)",
    "Block quotes (239)",
    "Block quotes (240)",
    "Block quotes (241)",
    "Block quotes (242)",
    "Block quotes (243)",
    "Block quotes (244)",
    "Block quotes (245)",
    "Block quotes (246)",
    "Block quotes (247)",
    "Block quotes (248)",
    "Block quotes (249)",
    "Block quotes (250)",
    "Block quotes (251)",
    "Block quotes (252)",
    "List items (253)",
    "List items (254)",
    "List items (255)",
    "List items (256)",
    "List items (257)",
    "List items (258)",
    "List items (259)",
    "List items (260)",
    "List items (261)",
    "List items (262)",
    "List items (263)",
    "List items (264)",
    "List items (265)",
    "List items (266)",
    "List items (267)",
    "List items (268)",
    "List items (269)",
    "List items (270)",
    "List items (271)",
    "List items (272)",
    "List items (273)",
    "List items (274)",
    "List items (275)",
    "List items (276)",
    "List items (277)",
    "List items (279)",
    "List items (280)",
    "List items (281)",
    "List items (282)",
    "List items (283)",
    "List items (284)",
    "List items (285)",
    "List items (286)",
    "List items (287)",
    "List items (288)",
    "List items (289)",
    "List items (290)",
    "List items (291)",
    "List items (292)",
    "List items (293)",
    "List items (294)",
    "List items (295)",
    "List items (296)",
    "List items (297)",
    "List items (298)",
    "List items (299)",
    "Lists (301)",
    "Lists (302)",
    "Lists (303)",
    "Lists (304)",
    "Lists (305)",
    "Lists (307)",
    "Lists (310)",
    "Lists (312)",
    "Lists (316)",
    "Lists (319)",
    "Lists (322)",
    "Lists (323)",
    "Lists (324)",
    "Lists (325)",
    "Inlines (327)",
    "Code spans (328)",
    "Code spans (329)",
    "Code spans (330)",
    "Code spans (331)",
    "Code spans (332)",
    "Code spans (333)",
    "Code spans (334)",
    "Code spans (338)",
    "Code spans (339)",
    "Code spans (340)",
    "Code spans (341)",
    "Code spans (342)",
    "Code spans (343)",
    "Code spans (344)",
    "Code spans (345)",
    "Code spans (347)",
    "Code spans (348)",
    "Code spans (349)",
    "Emphasis and strong emphasis (350)",
    "Emphasis and strong emphasis (351)",
    "Emphasis and strong emphasis (352)",
    "Emphasis and strong emphasis (353)",
    "Emphasis and strong emphasis (354)",
    "Emphasis and strong emphasis (355)",
    "Emphasis and strong emphasis (356)",
    "Emphasis and strong emphasis (357)",
    "Emphasis and strong emphasis (358)",
    "Emphasis and strong emphasis (359)",
    "Emphasis and strong emphasis (360)",
    "Emphasis and strong emphasis (361)",
    "Emphasis and strong emphasis (362)",
    "Emphasis and strong emphasis (363)",
    "Emphasis and strong emphasis (364)",
    "Emphasis and strong emphasis (365)",
    "Emphasis and strong emphasis (366)",
    "Emphasis and strong emphasis (367)",
    "Emphasis and strong emphasis (368)",
    "Emphasis and strong emphasis (369)",
    "Emphasis and strong emphasis (370)",
    "Emphasis and strong emphasis (371)",
    "Emphasis and strong emphasis (372)",
    "Emphasis and strong emphasis (373)",
    "Emphasis and strong emphasis (374)",
    "Emphasis and strong emphasis (375)",
    "Emphasis and strong emphasis (376)",
    "Emphasis and strong emphasis (377)",
    "Emphasis and strong emphasis (379)",
    "Emphasis and strong emphasis (380)",
    "Emphasis and strong emphasis (381)",
    "Emphasis and strong emphasis (383)",
    "Emphasis and strong emphasis (384)",
    "Emphasis and strong emphasis (385)",
    "Emphasis and strong emphasis (386)",
    "Emphasis and strong emphasis (387)",
    "Emphasis and strong emphasis (388)",
    "Emphasis and strong emphasis (391)",
    "Emphasis and strong emphasis (392)",
    "Emphasis and strong emphasis (393)",
    "Emphasis and strong emphasis (396)",
    "Emphasis and strong emphasis (397)",
    "Emphasis and strong emphasis (398)",
    "Emphasis and strong emphasis (400)",
    "Emphasis and strong emphasis (401)",
    "Emphasis and strong emphasis (404)",
    "Emphasis and strong emphasis (405)",
    "Emphasis and strong emphasis (407)",
    "Emphasis and strong emphasis (408)",
    "Emphasis and strong emphasis (409)",
    "Emphasis and strong emphasis (410)",
    "Emphasis and strong emphasis (411)",
    "Emphasis and strong emphasis (412)",
    "Emphasis and strong emphasis (413)",
    "Emphasis and strong emphasis (414)",
    "Emphasis and strong emphasis (415)",
    "Emphasis and strong emphasis (416)",
    "Emphasis and strong emphasis (417)",
    "Emphasis and strong emphasis (418)",
    "Emphasis and strong emphasis (419)",
    "Emphasis and strong emphasis (420)",
    "Emphasis and strong emphasis (421)",
    "Emphasis and strong emphasis (434)",
    "Emphasis and strong emphasis (435)",
    "Emphasis and strong emphasis (436)",
    "Emphasis and strong emphasis (437)",
    "Emphasis and strong emphasis (438)",
    "Emphasis and strong emphasis (439)",
    "Emphasis and strong emphasis (440)",
    "Emphasis and strong emphasis (441)",
    "Emphasis and strong emphasis (442)",
    "Emphasis and strong emphasis (443)",
    "Emphasis and strong emphasis (444)",
    "Emphasis and strong emphasis (445)",
    "Emphasis and strong emphasis (446)",
    "Emphasis and strong emphasis (447)",
    "Emphasis and strong emphasis (448)",
    "Emphasis and strong emphasis (449)",
    "Emphasis and strong emphasis (450)",
    "Emphasis and strong emphasis (451)",
    "Emphasis and strong emphasis (454)",
    "Emphasis and strong emphasis (455)",
    "Emphasis and strong emphasis (457)",
    "Emphasis and strong emphasis (459)",
    "Emphasis and strong emphasis (461)",
    "Emphasis and strong emphasis (463)",
    "Emphasis and strong emphasis (467)",
    "Emphasis and strong emphasis (469)",
    "Emphasis and strong emphasis (471)",
    "Emphasis and strong emphasis (472)",
    "Emphasis and strong emphasis (473)",
    "Emphasis and strong emphasis (474)",
    "Emphasis and strong emphasis (475)",
    "Emphasis and strong emphasis (476)",
    "Emphasis and strong emphasis (477)",
    "Emphasis and strong emphasis (478)",
    "Emphasis and strong emphasis (479)",
    "Emphasis and strong emphasis (480)",
    "Emphasis and strong emphasis (481)",
    "Links (482)",
    "Links (483)",
    "Links (485)",
    "Links (486)",
    "Links (487)",
    "Links (488)",
    "Links (490)",
    "Links (491)",
    "Links (492)",
    "Links (493)",
    "Links (494)",
    "Links (495)",
    "Links (496)",
    "Links (497)",
    "Links (498)",
    "Links (499)",
    "Links (500)",
    "Links (505)",
    "Links (506)",
    "Links (508)",
    "Links (509)",
    "Links (510)",
    "Links (511)",
    "Links (512)",
    "Links (513)",
    "Links (514)",
    "Links (515)",
    "Links (516)",
    "Links (517)",
    "Links (518)",
    "Links (519)",
    "Links (521)",
    "Links (522)",
    "Links (523)",
    "Links (524)",
    "Links (525)",
    "Links (527)",
    "Links (528)",
    "Links (529)",
    "Links (530)",
    "Links (531)",
    "Links (532)",
    "Links (533)",
    "Links (534)",
    "Links (535)",
    "Links (536)",
    "Links (537)",
    "Links (539)",
    "Links (540)",
    "Links (541)",
    "Links (542)",
    "Links (543)",
    "Links (545)",
    "Links (546)",
    "Links (547)",
    "Links (548)",
    "Links (549)",
    "Links (550)",
    "Links (551)",
    "Links (552)",
    "Links (553)",
    "Links (554)",
    "Links (555)",
    "Links (556)",
    "Links (557)",
    "Links (558)",
    "Links (559)",
    "Links (560)",
    "Links (561)",
    "Links (562)",
    "Links (563)",
    "Links (564)",
    "Links (565)",
    "Links (566)",
    "Links (567)",
    "Links (568)",
    "Links (569)",
    "Links (570)",
    "Links (571)",
    "Images (575)",
    "Images (578)",
    "Images (580)",
    "Images (581)",
    "Images (582)",
    "Images (583)",
    "Images (590)",
    "Images (592)",
    "Images (593)",
    "Autolinks (594)",
    "Autolinks (595)",
    "Autolinks (596)",
    "Autolinks (597)",
    "Autolinks (598)",
    "Autolinks (599)",
    "Autolinks (600)",
    "Autolinks (601)",
    "Autolinks (604)",
    "Autolinks (605)",
    "Autolinks (607)",
    "Autolinks (609)",
    "Autolinks (610)",
    "Raw HTML (613)",
    "Raw HTML (614)",
    "Raw HTML (615)",
    "Raw HTML (616)",
    "Raw HTML (617)",
    "Raw HTML (618)",
    "Raw HTML (619)",
    "Raw HTML (620)",
    "Raw HTML (621)",
    "Raw HTML (622)",
    "Raw HTML (623)",
    "Raw HTML (624)",
    "Raw HTML (626)",
    "Raw HTML (627)",
    "Raw HTML (628)",
    "Raw HTML (629)",
    "Raw HTML (630)",
    "Raw HTML (631)",
    "Raw HTML (632)",
    "Hard line breaks (633)",
    "Hard line breaks (634)",
    "Hard line breaks (635)",
    "Hard line breaks (636)",
    "Hard line breaks (637)",
    "Hard line breaks (638)",
    "Hard line breaks (639)",
    "Hard line breaks (642)",
    "Hard line breaks (643)",
    "Hard line breaks (644)",
    "Hard line breaks (645)",
    "Hard line breaks (646)",
    "Hard line breaks (647)",
    "Soft line breaks (648)",
    "Soft line breaks (649)",
    "Textual content (650)",
    "Textual content (651)",
    "Textual content (652)",
];

#[test]
fn commonmark_examples() {
    let examples = examples();
    assert!(examples.len() > 500, "suite found: {}", examples.len());
    let mut passed = Vec::new();
    let mut failed_expected = Vec::new();
    for (input, expected, name) in &examples {
        let got = render(input);
        if got == *expected {
            passed.push(name.as_str());
        } else if PASSING.contains(&name.as_str()) {
            failed_expected.push(format!("{name}\n--- expected\n{expected}--- got\n{got}"));
        }
    }
    eprintln!(
        "commonmark: {} of {} examples identical",
        passed.len(),
        examples.len()
    );
    if std::env::var_os("TMARK_COMMONMARK_LIST").is_some() {
        for name in &passed {
            eprintln!("PASS {name}");
        }
    }
    if std::env::var_os("TMARK_COMMONMARK_FAILS").is_some() {
        for (input, expected, name) in &examples {
            let got = render(input);
            if got != *expected {
                eprintln!("FAIL {name}\n--- input\n{input}--- expected\n{expected}--- got\n{got}");
            }
        }
    }
    assert!(
        failed_expected.is_empty(),
        "examples that used to pass:\n{}",
        failed_expected.join("\n")
    );
    for name in PASSING {
        assert!(
            passed.contains(name),
            "`{name}` is listed as passing but did not render"
        );
    }
}
