//! The TMark intermediate representation: the single source of truth for
//! what a document is.
//!
//! Design: `design/03-ir.md`. Spec: `spec/tmark.md` §Document model, §Node
//! catalogue, §Front matter, §Registries, §Feature registry, Appendix
//! "Deprecation schedule". This crate contains no parsing and no rendering;
//! everything else reads or writes these types.
//!
//! - [`span`]: files, byte spans, node ids, line index (spec §Round-trip and
//!   source spans).
//! - [`attrs`]: attribute lists (spec §Attributes).
//! - [`node`]: `Document`, `Block`, `Inline` and supporting types (spec §Node
//!   catalogue).
//! - [`table`]: the semantic table model (spec §Table).
//! - [`frontmatter`]: typed keys and YAML parsing (spec §Front matter).
//! - [`registry`]: the closed registries of roles, node words, prefixes,
//!   admonitions, features and deprecations.
//! - [`diagnostic`]: the one diagnostic type (design `05-diagnostics.md`).
//! - [`mod@walk`]: pre-order traversal.
//!
//! JSON schemas are generated by `cargo run -p tmark-ir --example schema`
//! into `crates/tmark-ir/schema/` (ADR 0003).

#![forbid(unsafe_code)]

pub mod attrs;
pub mod diagnostic;
pub mod frontmatter;
pub mod node;
pub mod registry;
pub mod span;
pub mod table;
pub mod walk;

pub use attrs::Attrs;
pub use diagnostic::{Code, Diagnostic, Fix, Severity};
pub use frontmatter::{
    AdmonitionDecl, Author, CounterDecl, Declare, Epigraph, FrontMatter, FrontMatterError, Keys,
    Press, Sources,
};
pub use node::{
    eq_with_spans, structural_json, Abbr, AbbrDef, Admonition, Aside, Block, BlockQuote,
    BulletList, Caption, CaptionKind, CaptionPosition, Code as CodeInline, CodeBlock, Comment,
    CounterItem, DefinitionList, Div, Document, Emph, Figure, Footnote, Header, Highlight,
    HorizontalRule, Image, Include, IndexEntry, Inline, Keystroke, LineBreak, Link, ListItem,
    ListStyle, Math, MathBlock, Meta, Note, OrderedList, Para, Plain, QuoteKind, Quoted, RawBlock,
    RawInline, Ref, RefItem, Side, SmallCaps, SoftBreak, Space, SpanNode, Str, Strikeout, Strong,
    Subscript, Superscript, Table, TableConfig, Target, Task, Underline, Var, SUGAR_FIELDS,
};
pub use registry::Scope;
pub use span::{FileId, LineCol, LineColUtf16, LineIndex, NodeId, Span, SubSpan};
pub use table::{
    Align, Cell, Column, ColumnConfig, ColumnGroup, DataRow, LeafColumn, Row, Separator,
    TableModel, TableSettings,
};
pub use walk::{find, nodes_at, plain_text, walk, walk_blocks, walk_inlines, NodeRef};

/// The JSON schema of a public shape, by name: `"ir"` (a `Document`),
/// `"frontmatter"` (the `Keys` of the front matter). The example
/// `schema` writes them under `schema/`; the CLI prints them.
pub fn schema(name: &str) -> Option<serde_json::Value> {
    let schema = match name {
        "ir" => schemars::schema_for!(Document),
        "frontmatter" => schemars::schema_for!(Keys),
        _ => return None,
    };
    serde_json::to_value(schema).ok()
}
