//! Writes the JSON schemas of the IR and of the front matter keys to
//! `crates/tmark-ir/schema/`. Run with `cargo run -p tmark-ir --example schema`
//! and commit the output (design `03-ir.md` §Serialization).

use std::path::Path;

use schemars::schema::RootSchema;
use schemars::schema_for;
use tmark_ir::{Document, Keys};

fn write(dir: &Path, name: &str, mut schema: RootSchema) {
    let own = schema
        .schema
        .metadata()
        .description
        .clone()
        .unwrap_or_default();
    schema.schema.metadata().description = Some(format!(
        "Generated by `cargo run -p tmark-ir --example schema` from the Rust types of tmark-ir; do not edit. {own}"
    ));
    let path = dir.join(name);
    let json = serde_json::to_string_pretty(&schema).expect("schema serialises");
    std::fs::write(&path, json + "\n").unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    println!("wrote {}", path.display());
}

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("schema");
    std::fs::create_dir_all(&dir).expect("schema directory");
    write(&dir, "ir.json", schema_for!(Document));
    write(&dir, "frontmatter.json", schema_for!(Keys));
}
