#!/usr/bin/env python3
"""Generate `python/tmark/_tmark.pyi` from the built native module.

    maturin develop -m crates/tmark-py/Cargo.toml
    python3 crates/tmark-py/scripts/gen_stubs.py [--check]

The first line of every function's docstring in `src/lib.rs` is its Python
signature; the rest is the description. This script reads them from the
imported module, so the stub has one source (AGENTS.md, SSOT). `--check`
exits 1 when the committed stub differs (CI).
"""

from __future__ import annotations

import inspect
import pathlib
import sys
import textwrap

HERE = pathlib.Path(__file__).resolve().parent
STUB = HERE.parent / "python" / "tmark" / "_tmark.pyi"

HEADER = '''"""Generated by scripts/gen_stubs.py from the docstrings of tmark._tmark; do not edit."""

from __future__ import annotations

from typing import Any, Protocol

class Loader(Protocol):
    def load(self, from_path: str, rel: str) -> str | None: ...

__version__: str

'''


def signature_of(name: str, fn) -> tuple[str, str]:
    """The (signature, description) of a docstring whose first line is the signature."""
    doc = (fn.__doc__ or "").strip()
    if not doc:
        sys.exit(f"{name}: no docstring")
    signature, _, rest = doc.partition("\n")
    if not signature.startswith(f"{name}("):
        sys.exit(f"{name}: the docstring must start with its signature, got {signature!r}")
    return signature, rest.strip()


def function(name: str, fn, indent: str = "") -> str:
    signature, rest = signature_of(name, fn)
    if indent:
        args = signature[len(name) + 1 :]
        signature = f"{name}(self{args}" if args.startswith(")") else f"{name}(self, {args}"
    out = f"{indent}def {signature}:\n"
    if rest:
        out += f'{indent}    """\n{textwrap.indent(rest, indent + "    ")}\n{indent}    """\n'
    return out + f"{indent}    ...\n"


def render(module) -> str:
    out = [HEADER]
    for name, cls in inspect.getmembers(module, inspect.isclass):
        if name.startswith("_") or cls.__module__ != module.__name__:
            continue
        out.append(f"class {name}:\n")
        doc = (cls.__doc__ or "").strip()
        if doc:
            out.append(f'    """\n{textwrap.indent(doc, "    ")}\n    """\n')
        if "__repr__" in vars(cls):
            out.append("    def __repr__(self) -> str: ...\n")
        for member, fn in sorted(vars(cls).items()):
            if callable(fn) and not member.startswith("_"):
                out.append(function(member, fn, "    "))
        out.append("\n")
    for name, fn in inspect.getmembers(module, inspect.isbuiltin):
        if not name.startswith("_"):
            out.append(function(name, fn) + "\n")
    return "".join(out).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    import tmark._tmark as native

    text = render(native)
    if "--check" in argv:
        current = STUB.read_text() if STUB.exists() else ""
        if current != text:
            print(f"{STUB} is out of date; run {pathlib.Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{STUB.name} up to date")
        return 0
    STUB.write_text(text)
    print(f"wrote {STUB}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
