#!/usr/bin/env python3
"""Generate `python/tmark/_tmark.pyi` from the built native module.

    maturin develop -m crates/tmark-py/Cargo.toml
    python3 crates/tmark-py/scripts/gen_stubs.py [--check]

The first line of every function's docstring in `src/lib.rs` is its Python
signature; the rest is the description. This script reads them from the
imported module, so the stub has one source (AGENTS.md, SSOT). `--check`
exits 1 when the committed stub differs (CI).
"""

from __future__ import annotations

import inspect
import pathlib
import sys
import textwrap

HERE = pathlib.Path(__file__).resolve().parent
STUB = HERE.parent / "python" / "tmark" / "_tmark.pyi"

HEADER = '''"""Generated by scripts/gen_stubs.py from the docstrings of tmark._tmark; do not edit."""

from __future__ import annotations

from typing import Any, Protocol

class Loader(Protocol):
    def load(self, from_path: str, rel: str) -> str | None: ...

__version__: str

'''


def render(module) -> str:
    out = [HEADER]
    for name, fn in inspect.getmembers(module, inspect.isbuiltin):
        if name.startswith("_"):
            continue
        doc = (fn.__doc__ or "").strip()
        if not doc:
            sys.exit(f"{name}: no docstring")
        signature, _, rest = doc.partition("\n")
        if not signature.startswith(f"{name}("):
            sys.exit(f"{name}: the docstring must start with its signature, got {signature!r}")
        body = textwrap.indent(rest.strip(), "    ")
        out.append(f"def {signature}:\n")
        out.append(f'    """\n{body}\n    """\n')
        out.append("    ...\n\n")
    return "".join(out).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    import tmark._tmark as native

    text = render(native)
    if "--check" in argv:
        current = STUB.read_text() if STUB.exists() else ""
        if current != text:
            print(f"{STUB} is out of date; run {pathlib.Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{STUB.name} up to date")
        return 0
    STUB.write_text(text)
    print(f"wrote {STUB}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
