#!/usr/bin/env python3
"""Regenerate the emoji shortcode table of `tmark-ir` from GitHub's gemoji.

    python3 scripts/gen-emoji.py [path/to/emoji.json]

Without an argument the script downloads `db/emoji.json` from
https://github.com/github/gemoji (the name table spec §Emoji and icon
shortcodes prescribes; `pymdownx.emoji` ships the same index as `gemoji`).
The output, `crates/tmark-ir/src/emoji/table.rs`, is a sorted `const` slice
of `(shortcode, character)` pairs, one per alias, so the crate stays
dependency-free and looks a name up by binary search. Commit the output.
"""
import json
import pathlib
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/tmark-ir/src/emoji/table.rs"
URL = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"


def load(argv):
    if argv:
        return json.loads(pathlib.Path(argv[0]).read_text(encoding="utf-8")), argv[0]
    with urllib.request.urlopen(URL, timeout=30) as response:
        return json.load(response), URL


def escape(text):
    return "".join(f"\\u{{{ord(c):x}}}" for c in text)


def main(argv):
    entries, source = load(argv)
    rows = {}
    for entry in entries:
        char = entry.get("emoji")
        if not char:
            continue
        for alias in entry.get("aliases", []):
            rows.setdefault(alias, char)
    lines = [
        "// Generated by `scripts/gen-emoji.py`; do not edit.",
        f"// Source: {source} (github/gemoji `db/emoji.json`,",
        f"// {len(entries)} entries, {len(rows)} shortcodes).",
        "",
        "/// `(shortcode, character)` pairs, sorted by shortcode (bytewise) for",
        "/// binary search. Spec §Emoji and icon shortcodes: the `gemoji` names.",
        "pub const EMOJI: &[(&str, &str)] = &[",
    ]
    for alias in sorted(rows):
        lines.append(f'    ("{alias}", "{escape(rows[alias])}"),')
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} shortcodes)")


if __name__ == "__main__":
    main(sys.argv[1:])
