"""Generated by scripts/gen_stubs.py from the docstrings of tmark._tmark; do not edit."""

from __future__ import annotations

from typing import Any, Protocol

class Loader(Protocol):
    def load(self, from_path: str, rel: str) -> str | None: ...

__version__: str

class Resolved:
    """
    The opaque handle `resolve` returns next to its JSON view, so that
    `write` renders every slot of a document against one resolution
    (numbering never restarts per slot). `Resolved` is not rebuilt from
    its view: the view is for reading, the handle for writing.
    """
    def __repr__(self) -> str: ...
    def view(self) -> dict[str, Any]:
        """
        The JSON view of this resolution (`schema("resolved")`, without
        the `line`/`col` of `resolve`).
        """
        ...

def codes() -> list[dict[str, Any]]:
    """
    The diagnostic catalogue in order: `{"id", "severity", "stage", "doc"}`
    per code, `severity` being the default one and `stage` `parse`,
    `resolve` or `lint` (design 05 §Who emits what).
    """
    ...

def edit(text: str, doc: dict[str, Any], node_id: int, replacement: dict[str, Any]) -> str:
    """
    Replace one node of `text` (the source `doc` was parsed from) by the
    canonical spelling of `replacement`, a Block or Inline node as JSON,
    leaving every other byte untouched (design 04 §Local edits, ADR 0004).
    Raises `ValueError` when `node_id` is not in the document.
    """
    ...

def edit_many(text: str, doc: dict[str, Any], edits: list[dict[str, Any]]) -> str:
    """
    Apply several local edits in one pass: each item is
    `{"node_id": int, "replacement": dict}` with the replacement shape of
    `edit`. Spans must be disjoint; an unknown node, a span outside the
    text or two overlapping edits raise `ValueError` and nothing is applied
    (design 04 §Local edits).
    """
    ...

def fixes(text: str, file: str = "<memory>", loader: Loader | None = None, options: dict[str, Any] | None = None) -> str:
    """
    The text with every safe fix applied: what `tmark lint --fix` writes
    (deprecated spellings rewritten in their canonical form, design 05
    §Fixes). `loader` and `options` are those of `lint`. The text comes back
    unchanged when nothing has a fix.
    """
    ...

def format(text: str, profile: str = "canonical") -> str:
    """
    The canonical spelling of a text (design 04): `parse(format(text))`
    is `parse(text)` and `format` is idempotent. The front matter is copied
    byte for byte and prose is never re-wrapped.
    """
    ...

def fragments() -> list[dict[str, Any]]:
    """
    The fragment-contract table (design 07): one row per contract a
    writer's `requires.fragments` can name, `{"name", "provides",
    "packages", "shell_escape", "description"}`.
    """
    ...

def lint(text: str, file: str = "<memory>", loader: Loader | None = None, options: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    """
    Every diagnostic of a text: parse, resolve and lint, in that order,
    with fixes attached (`tmark check`). Includes and sources load through
    `loader` (the file system when `None`) relative to `options["path"]`
    (`file` when it is a real path). `options` accepts `path`,
    `bibliography` (list of `.bib` paths), `start` (prefix -> first value),
    `numbering` (`backend` or `all`), `lang`, `book` (sibling labels),
    `profile` and `levels` (code -> `off`/`hint`/`info`/`warning`/`error`).
    Each diagnostic is the JSON of `tmark_ir::Diagnostic` (`code` as its
    kebab-case id) plus `stage`, `path`, `line` and `col` (1-based, byte
    column; `None` for another file).
    """
    ...

def lower_web(text: str, doc: dict[str, Any], resolved: Resolved | dict[str, Any] | None = None, loader: Loader | None = None, options: dict[str, Any] | None = None) -> dict[str, Any]:
    """
    Lower a page for a MkDocs site (design 07 §Web lowering, TeXSmith
    `web-profile.md`): `text` is the source `doc` was parsed from; every
    TMark construct of the per-construct table is spliced into what
    Material renders (`<span class="ts-counter">FW-01</span>`,
    `[FW-01](#fw:x)`, `<figure markdown="span">`, `!!! note`, sibling
    links) and every other byte is kept, mkdocstrings directives
    included. `resolved` is the `resolve` result or its `handle`, made
    with `numbering: "all"` and the site's `book`; `None` resolves now
    through `loader` with every series numbered. `loader` also serves the
    text of included files (the file system when `None`). `options`:
    `sections` (`title` | `number`, what `@sec:x` shows), `citations`
    (`inline` | `passthrough`), `lang`, `css_prefix` (`ts-`); an unknown
    key or value is a `TypeError`. Returns `{"text", "diagnostics",
    "bibliography"}`: the lowered page (the `References` list appended
    when citations were lowered inline), the lowering's own diagnostics
    (with `line`/`col`), and the `References` list alone or `None`.
    """
    ...

def parse(text: str, file: str = "<memory>", file_id: int = 0, profile: str = "default") -> dict[str, Any]:
    """
    Parse a TMark text. Returns the document as JSON (design 03 §Serialization)
    with `"tmark": "<version>"` as its first key and the parse `"diagnostics"`
    as its last. `file` names the text in the diagnostics; `file_id` is the
    id every span carries; `profile` is `default` (`canonical`), `strict`
    or `mkdocs`. Parsing never fails.
    """
    ...

def registries() -> dict[str, Any]:
    """
    The closed registries of the IR as tables (design 03 §Closed
    registries): `roles`, `node_words`, `lang_default_node_words`,
    `prefixes`, `admonitions`, `features`, `deprecations`, `key_labels`
    (keystroke name -> label). One definition, in `tmark_ir::registry`;
    generate from these, never copy them.
    """
    ...

def resolve(doc: dict[str, Any], loader: Loader | None = None, options: dict[str, Any] | None = None, text: str | None = None) -> dict[str, Any]:
    """
    Build the registries of a parsed document and resolve its references
    (design 06). `doc` is a `parse` result (its `"tmark"` version must
    match); `loader` and `options` are those of `lint` (`path`,
    `bibliography`, `start`, `numbering`, `lang`, `book`). The result is
    `schema("resolved")`: `numbering` and `lang` as used, `counters` (every
    series with its `numbers` and `next`), `next_start` (prefix -> the
    first free value, for the next document of a build), `labels` (in
    document order, with `formatted` numbers), `book` (this document's
    labels for its siblings, located at `path#key`), `refs` (one per
    reference, `resolution.kind` in `label`, `sibling`, `citation`,
    `glossary`, `doi`, `external`, `ambiguous`, `unresolved`),
    `bibliography` (keys), `entries`, `dois` (pending), `glossary`, `index`,
    `crossrefs`, `included` (files loaded through includes), `diagnostics`
    and `handle`, an opaque `tmark.Resolved` that `write` takes (pass this
    whole dict, or the handle, as its `resolved`). Pass `text` to get
    `line` and `col` on the diagnostics of the main file.
    """
    ...

def schema(name: str) -> dict[str, Any]:
    """
    A JSON schema by name: `ir` (a document), `frontmatter` (the typed
    keys), `diagnostic` (one diagnostic), `resolved` (a `resolve` result).
    Generated from the Rust types (ADR 0003); TeXSmith generates its models
    from `ir` and checks `schema_hash()` against the one it recorded.
    """
    ...

def schema_hash() -> str:
    """
    A stable hash of `schema("ir")` (16 hexadecimal digits, the same on
    every platform): equal for two builds whose IR shapes are identical.
    """
    ...

def version() -> str:
    """
    The version of the native module, the one the IR JSON root carries.
    """
    ...

def write(doc: dict[str, Any], backend: str, options: dict[str, Any] | None = None, loader: Loader | None = None, resolved: Resolved | dict[str, Any] | None = None, resolve_options: dict[str, Any] | None = None) -> dict[str, Any]:
    """
    Render a document for a backend (`html`, `latex`, `typst`): a `Body`
    as `{"text", "map", "requires"}` (design 07). `map` is
    `[[start, end, node_id], ...]` over the output bytes, filled when
    `options["source_map"]` is on; `requires` lists `packages`,
    `fragments`, `shell_escape`, `assets`, `bibliography`, `citations`,
    `acronyms`, `index` and `counters`. `options` maps one to one onto
    `WriterOptions`, every key optional: `media` (`print` | `web`), `lang`,
    `code` {`engine` (`pygments` | `minted` | `listings` | `verbatim`),
    `inline_plain`, `inline_breaks`}, `latex` {`legacy_accents`},
    `headings` {`base_level`, `numbered`}, `refs` {`textual_print`,
    `textual_web`}, `numbering` (prefix -> `backend` | `tmark`), `typst`
    {`math` (`mitex` | `native`)}, `source_map`. An unknown key is a
    `TypeError`, a bad value a `ValueError`. `resolved` is the dict
    `resolve` returned, or its `handle`: pass the same one for every slot
    of a document so numbering never restarts; `None` resolves now, through
    `loader` with `resolve_options` (the `options` of `resolve`).
    """
    ...
